#!/usr/bin/env python3
"""
Feed-Phil city kit — map engine.
Reads:  city.json  (CITY/HOTEL/GROUPS/VENUES — exported from city.js)
        city_geo.json (stations, transit lines, streets, landmarks, parks,
                       neighbourhoods, overview + area specs)
        basemaps/<name>.png (OPTIONAL — see fetch_basemaps.py / ../LIVE_MAPS.md)
Writes: maps.json  (inline SVGs: 'overview' + one 'area_<groupid>' per group)

Everything city-specific lives in the two JSON inputs — do not edit this file
per city. See template/SCHEMA.md for field docs.

Live basemaps (optional): if basemaps/overview.png or basemaps/area_<gid>.png
exists (produced by fetch_basemaps.py, run locally or via the desktop
bridge — this sandbox usually can't reach map services directly), that real
map image is composited in as the background in place of the hand-drawn
streets/parks, sized to exactly match the map's bounds. Everything else —
transit lines, stations, landmarks, venue pins, hotel marker, scale bar,
north arrow — is drawn on top in both modes, with a light text halo added
automatically when a photo basemap is underneath so labels stay legible.
No basemaps present -> output is unchanged from the pure-schematic look.
"""
import json, math, sys, os, base64

BASE = os.path.dirname(os.path.abspath(__file__))
WORK = os.getcwd()

D = json.load(open(os.path.join(WORK, 'city.json')))
G = json.load(open(os.path.join(WORK, 'city_geo.json')))
HOTEL, GROUPS, VENUES = D['HOTEL'], D['GROUPS'], D['VENUES']

LINE_COLORS = G['line_colors']          # {"L9": "#A60084", ...}
ST = G['stations']                       # {"Name": {"lines": [...], "lat":, "lon":}}
TRANSIT_LINES = G['transit_lines']       # [{"line": "L9", "path": ["St A","St B",...]}]
ANNOTATIONS = G.get('annotations', [])   # [{"from_station":, "dx":, "dy":, "color":, "label":}]
STREETS = G['streets']                   # {"key": {"name": str|null, "path": [[lat,lon],...]}}
LANDMARKS = G['landmarks']               # {"id": {"label":, "lat":, "lon":}}
PARKS = G['parks']                       # {"id": {"label":, "lat_min":, "lat_max":, "lon_min":, "lon_max":}}
NEIGHBOURHOODS = G.get('neighbourhoods', [])  # [{"label":, "lat":, "lon":}]
OV = G['overview']                       # bounds, street lists, label offset dicts...
AREAS = G['areas']                       # per-group stroll map specs

BASEMAP_DIR = os.path.join(WORK, 'basemaps')

LAT0 = (OV['bounds'][0] + OV['bounds'][1]) / 2
M_PER_LAT = 110574.0
M_PER_LON = 111320.0 * math.cos(math.radians(LAT0))

def make_proj(lat_min, lat_max, lon_min, lon_max, width):
    w_m = (lon_max-lon_min)*M_PER_LON
    h_m = (lat_max-lat_min)*M_PER_LAT
    height = width*h_m/w_m
    def proj(lat, lon):
        x = (lon-lon_min)/(lon_max-lon_min)*width
        y = (lat_max-lat)/(lat_max-lat_min)*height
        return round(x,1), round(y,1)
    return proj, height, width/w_m

def esc(s): return s.replace('&','&amp;').replace('<','&lt;')

# When a real basemap photo sits underneath, labels need a light halo to stay
# readable over varied imagery. Injected as extra <text> attributes — a
# single element can stroke-then-fill via paint-order, no duplicate needed.
HALO_ATTR = 'stroke="#FBF7EF" stroke-width="3" stroke-linejoin="round" paint-order="stroke" '
def halo(on): return HALO_ATTR if on else ''

def load_basemap_b64(name):
    """Return a base64 data URI for basemaps/<name>.png, or None if absent."""
    path = os.path.join(BASEMAP_DIR, f'{name}.png')
    if not os.path.isfile(path):
        return None
    with open(path, 'rb') as f:
        data = f.read()
    return 'data:image/png;base64,' + base64.b64encode(data).decode('ascii')

def station_dot(x,y,r=4.2):
    return f'<circle cx="{x}" cy="{y}" r="{r}" fill="#fff" stroke="#2B2118" stroke-width="1.6"/>'

def draw_streets(s, proj, keys, width_px=5, label_size=7.6, label_keys=None, halo_on=False):
    for k in keys:
        st = STREETS[k]
        pp = [proj(a,b) for a,b in st['path']]
        ptstr = ' '.join(f'{x},{y}' for x,y in pp)
        s.append(f'<polyline points="{ptstr}" fill="none" stroke="#E6DECD" stroke-width="{width_px}" stroke-linecap="round" stroke-linejoin="round"/>')
    for k in (label_keys if label_keys is not None else keys):
        st = STREETS[k]
        if not st.get('name'): continue
        pp = [proj(a,b) for a,b in st['path']]
        i = len(pp)//2
        (x1,y1),(x2,y2) = pp[max(0,i-1)], pp[min(len(pp)-1,i)]
        ang = math.degrees(math.atan2(y2-y1, x2-x1))
        if ang > 90: ang -= 180
        if ang < -90: ang += 180
        mx,my = (x1+x2)/2, (y1+y2)/2
        s.append(f'<text x="{mx}" y="{my-3}" font-size="{label_size}" fill="#B4A88F" {halo(halo_on)}text-anchor="middle" transform="rotate({ang:.0f} {mx} {my-3})">{esc(st["name"])}</text>')

def draw_park(s, proj, pid, label_size=10, canvas=None):
    p = PARKS[pid]
    x1,y1 = proj(p['lat_max'], p['lon_min']); x2,y2 = proj(p['lat_min'], p['lon_max'])
    s.append(f'<rect x="{x1}" y="{y1}" width="{x2-x1:.1f}" height="{y2-y1:.1f}" rx="10" fill="#D9E9CD" stroke="#BCD4A8" stroke-width="1"/>')
    lx, ly = (x1+x2)/2, (y1+y2)/2+3
    if canvas:
        W,H = canvas
        lx = min(max(lx, x1+30, 30), x2-30, W-30)
        ly = min(max(ly, y1+16, 16), y2-10, H-14)
    s.append(f'<text x="{lx:.1f}" y="{ly:.1f}" font-size="{label_size}" fill="#6D8A55" text-anchor="middle" font-style="italic">{esc(p["label"])}</text>')

def draw_landmark(s, x, y, label, size=8.6, anchor='start', dx=7, dy=3, color='#5E5343', halo_on=False):
    s.append(f'<rect x="{x-3.4}" y="{y-3.4}" width="6.8" height="6.8" fill="#7A6C5D" stroke="#fff" stroke-width="1.2" transform="rotate(45 {x} {y})"/>')
    s.append(f'<text x="{x+dx if anchor=="start" else x-dx}" y="{y+dy}" font-size="{size}" fill="{color}" {halo(halo_on)}text-anchor="{anchor}" font-weight="bold">{esc(label)}</text>')

def scale_bar(s, m2px, H, meters, x0=20, label=None):
    bar = meters*m2px
    by = H-22 if meters >= 1000 else H-14
    lab = label or (f'{meters/1000:.0f} km' if meters >= 1000 else f'{meters:.0f} m')
    s.append(f'<line x1="{x0}" y1="{by}" x2="{x0+bar:.0f}" y2="{by}" stroke="#2B2118" stroke-width="2"/>'
             f'<line x1="{x0}" y1="{by-4}" x2="{x0}" y2="{by+4}" stroke="#2B2118" stroke-width="2"/>'
             f'<line x1="{x0+bar:.0f}" y1="{by-4}" x2="{x0+bar:.0f}" y2="{by+4}" stroke="#2B2118" stroke-width="2"/>'
             f'<text x="{x0+bar/2:.0f}" y="{by-7}" font-size="9" fill="#2B2118" text-anchor="middle">{lab}</text>')

def hotel_marker(s, hx, hy, r=12, label='Your base', label_anchor='start', halo_on=False):
    s.append(f'<circle cx="{hx}" cy="{hy}" r="{r}" fill="#2B2118" stroke="#fff" stroke-width="2.5"/>'
             f'<text x="{hx}" y="{hy+4.5}" font-size="{r+1}" fill="#FFD766" text-anchor="middle">★</text>')
    tx = hx+r+4 if label_anchor=='start' else hx-r-4
    s.append(f'<text x="{tx}" y="{hy+4}" font-size="10.5" font-weight="bold" fill="#2B2118" {halo(halo_on)}text-anchor="{label_anchor}">{esc(label)}</text>')

def venue_pin(s, x, y, num, color, r=10.5):
    s.append(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{color}" stroke="#fff" stroke-width="2.4"/>'
             f'<text x="{x}" y="{y+r*0.38}" font-size="{r+0.5}" fill="#fff" text-anchor="middle" font-weight="bold">{num}</text>')

# ------------------------------------------------------------------ overview
def overview_svg():
    W = OV.get('width', 760)
    la0,la1,lo0,lo1 = OV['bounds']
    proj, H, m2px = make_proj(la0,la1,lo0,lo1,W)
    s = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H:.0f}" font-family="Helvetica,Arial,sans-serif">']
    s.append(f'<rect width="{W}" height="{H:.0f}" fill="#FBF7EF" rx="10"/>')

    bg = load_basemap_b64('overview')
    has_bg = bg is not None
    if has_bg:
        s.append(f'<clipPath id="ovclip"><rect width="{W}" height="{H:.0f}" rx="10"/></clipPath>')
        s.append(f'<image href="{bg}" x="0" y="0" width="{W}" height="{H:.0f}" preserveAspectRatio="none" clip-path="url(#ovclip)"/>')
    else:
        for pid in OV.get('parks', list(PARKS.keys())): draw_park(s, proj, pid)
        for group in OV.get('street_layers', []):       # [{"keys": [...], "width": 9}]
            draw_streets(s, proj, group['keys'], width_px=group.get('width',5),
                         label_keys=group.get('label_keys'))

    for nb in NEIGHBOURHOODS:
        x,y = proj(nb['lat'], nb['lon'])
        s.append(f'<text x="{x}" y="{y}" font-size="9.5" fill="#C9BCA1" {halo(has_bg)}text-anchor="middle" letter-spacing="1.6">{esc(nb["label"])}</text>')

    for tl in TRANSIT_LINES:
        pts = ' '.join(f'{proj(ST[n]["lat"],ST[n]["lon"])[0]},{proj(ST[n]["lat"],ST[n]["lon"])[1]}' for n in tl['path'])
        s.append(f'<polyline points="{pts}" fill="none" stroke="{LINE_COLORS[tl["line"]]}" stroke-width="3.4" stroke-linecap="round" stroke-linejoin="round" opacity="0.8"/>')
    for an in ANNOTATIONS:
        st = ST[an['from_station']]
        x,y = proj(st['lat'], st['lon'])
        s.append(f'<line x1="{x}" y1="{y}" x2="{x+an["dx"]}" y2="{y+an["dy"]}" stroke="{an["color"]}" stroke-width="3.4" stroke-dasharray="7 5" stroke-linecap="round"/>')
        s.append(f'<text x="{x+an["label_dx"]}" y="{y+an["label_dy"]}" font-size="9.5" fill="{an.get("label_color", an["color"])}" {halo(has_bg)}font-weight="bold" text-anchor="{an.get("label_anchor","end")}">{esc(an["label"])}</text>')

    st_show = OV.get('station_labels', {})   # {"Name": [dx,dy]}
    skip = set(OV.get('station_skip', []))
    for name, st in ST.items():
        if name in skip: continue
        x,y = proj(st['lat'], st['lon'])
        s.append(station_dot(x,y,3.6))
        if name in st_show:
            dx,dy = st_show[name]
            s.append(f'<text x="{x+dx}" y="{y+dy}" font-size="8.2" fill="#5E5343" {halo(has_bg)}>{esc(name)}</text>')

    for lid, style in OV.get('landmark_labels', {}).items():   # {"id": [anchor,dx,dy]}
        anchor,dx,dy = style
        lm = LANDMARKS[lid]
        x,y = proj(lm['lat'], lm['lon'])
        draw_landmark(s, x, y, lm['label'], anchor=anchor, dx=abs(dx), dy=dy, halo_on=has_bg)

    hx,hy = proj(*HOTEL['coords'])
    hotel_marker(s, hx, hy, label=OV.get('hotel_label','Your base'),
                 label_anchor=OV.get('hotel_label_anchor','start'), halo_on=has_bg)

    lab = OV['venue_labels']                 # {"venueid": [dx,dy,anchor]}
    disp = OV.get('venue_display_offsets', {})  # {"venueid": [dx,dy]} nudge overlapping pins
    for v in VENUES:
        c = GROUPS[v['group']]['color']
        x,y = proj(*v['coords'])
        ddx,ddy = disp.get(v['id'],(0,0)); x+=ddx; y+=ddy
        venue_pin(s, x, y, v['num'], c)
        dx,dy,anc = lab[v['id']]
        nm = v['name'].split('·')[0].strip()
        s.append(f'<text x="{x+dx}" y="{y+dy}" font-size="9.6" font-weight="bold" fill="{c}" {halo(has_bg)}text-anchor="{anc}">{esc(nm)}</text>')

    scale_bar(s, m2px, H, OV.get('scale_m', 1000))
    s.append(f'<text x="{W-24}" y="30" font-size="16" fill="#2B2118" {halo(has_bg)}text-anchor="middle">▲</text>'
             f'<text x="{W-24}" y="42" font-size="9" fill="#2B2118" {halo(has_bg)}text-anchor="middle">N</text>')
    s.append('</svg>')
    return ''.join(s)

# ------------------------------------------------------------------ stroll areas
def area_svg(gid):
    A = AREAS[gid]
    W = A.get('width', 640)
    la0,la1,lo0,lo1 = A['bounds']
    proj, H, m2px = make_proj(la0,la1,lo0,lo1,W)
    color = GROUPS[gid]['color']
    s = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H:.0f}" font-family="Helvetica,Arial,sans-serif">']
    s.append(f'<rect width="{W}" height="{H:.0f}" fill="#FBF7EF" rx="8"/>')

    bg = load_basemap_b64(f'area_{gid}')
    has_bg = bg is not None
    if has_bg:
        s.append(f'<clipPath id="clip-{gid}"><rect width="{W}" height="{H:.0f}" rx="8"/></clipPath>')
        s.append(f'<image href="{bg}" x="0" y="0" width="{W}" height="{H:.0f}" preserveAspectRatio="none" clip-path="url(#clip-{gid})"/>')
    else:
        for pid in A.get('parks', []): draw_park(s, proj, pid, label_size=11, canvas=(W,H))
        draw_streets(s, proj, A['streets'], width_px=7, label_size=8.8, label_keys=A.get('label_streets'))

    for n in A.get('stations', []):
        st = ST[n]
        x,y = proj(st['lat'], st['lon'])
        if not (-10 <= x <= W+10 and -10 <= y <= H+10): continue
        s.append(station_dot(x,y,4.6))
        odx, ody = A.get('station_labels', {}).get(n, (None,None))
        flip = (odx is not None and odx < 0) or (odx is None and x > W-96)
        anch = 'end' if flip else 'start'
        tx = x + (odx if odx is not None else (-8 if flip else 8))
        ty = y + (ody if ody is not None else 3.6)
        s.append(f'<text x="{tx}" y="{ty}" font-size="8.6" fill="#8B8378" {halo(has_bg)}text-anchor="{anch}">'
                 f'{esc(n)} <tspan font-weight="bold" fill="#6b6257">({"/".join(st["lines"])})</tspan></text>')

    for lid, style in A.get('landmarks', {}).items():
        anchor,dx,dy = style
        lm = LANDMARKS[lid]
        x,y = proj(lm['lat'], lm['lon'])
        if not (0 <= x <= W and 0 <= y <= H): continue
        draw_landmark(s, x, y, lm['label'], size=9.4, anchor=anchor, dx=abs(dx), dy=dy, color='#4A3F30', halo_on=has_bg)

    if A.get('show_hotel'):
        hx,hy = proj(*HOTEL['coords'])
        hotel_marker(s, hx, hy, r=11, label=OV.get('hotel_label','Your base'),
                     label_anchor=A.get('hotel_label_anchor','end'), halo_on=has_bg)

    lab = A['venue_labels']
    disp = A.get('venue_display_offsets', {})
    for v in VENUES:
        if v['group'] != gid: continue
        x,y = proj(*v['coords'])
        ddx,ddy = disp.get(v['id'],(0,0)); x+=ddx; y+=ddy
        venue_pin(s, x, y, v['num'], color, r=11.5)
        dx,dy,anc = lab[v['id']]
        nm = v['name'].split('·')[0].strip()
        s.append(f'<text x="{x+dx}" y="{y+dy}" font-size="10.4" font-weight="bold" fill="{color}" {halo(has_bg)}text-anchor="{anc}">{esc(nm)}</text>')

    scale_bar(s, m2px, H, A.get('scale_m', 250), x0=16)
    s.append(f'<text x="{W-16}" y="18" font-size="12" fill="#8B8378" {halo(has_bg)}text-anchor="middle">▲N</text>')
    s.append('</svg>')
    return ''.join(s)

out = {'overview': overview_svg()}
for gid in AREAS:
    out['area_'+gid] = area_svg(gid)
json.dump(out, open(os.path.join(WORK,'maps.json'),'w'))

n_live = sum(1 for name in ['overview'] + [f'area_{g}' for g in AREAS]
             if os.path.isfile(os.path.join(BASEMAP_DIR, f'{name}.png')))
mode = f'{n_live} live basemap(s) + schematic overlay' if n_live else 'schematic (no basemaps/ found)'
print(f'gen_maps: overview + {len(AREAS)} area maps -> maps.json  [{mode}]')
